---
title: "NFL Attendance - Feb 05, 2020"
date: '`r Sys.Date()`'
output: github_document
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(cache = TRUE, warning = FALSE, message = FALSE, 
                      echo = TRUE, dpi = 300, cache.lazy = FALSE,
                      tidy = "styler", fig.width = 8, fig.height = 5)
library(tidyverse)
```

Here the goal is to build a model to predict weekly attendance for teams in NFL games.

## Explore Data

```{r}
attendance <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-04/attendance.csv")
standings <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-04/standings.csv")

attendance_joined <- attendance %>%
  left_join(standings,
    by = c("year", "team_name", "team")
  )

attendance_joined
```

```{r}
attendance_joined %>% 
  filter(!is.na(weekly_attendance)) %>% 
  ggplot(aes(fct_reorder(team_name, weekly_attendance),
             weekly_attendance,
             fill = playoffs)) +
  geom_boxplot(outlier.alpha = 0.5) +
  coord_flip()
```

```{r}
attendance_joined %>% 
  distinct(team_name, year, margin_of_victory, playoffs)

attendance_joined %>% 
  distinct(team_name, year, margin_of_victory, playoffs) %>% 
  ggplot(aes(margin_of_victory, fill = playoffs)) +
  geom_histogram(postition = "identity", alpha = 0.7)
```


```{r}
attendance_joined %>% 
  mutate(week = factor(week)) %>% 
  ggplot(aes(week, weekly_attendance, fill = week)) +
  geom_boxplot(show.legend = FALSE, outlier.alpha = 0.5)
```


```{r}
attendance_df <- attendance_joined %>% 
  filter(!is.na(weekly_attendance)) %>% 
  select(weekly_attendance, team_name, week, 
         margin_of_victory, strength_of_schedule, playoffs)

attendance_df
```

## Train model

```{r}
library(tidymodels)

set.seed(1234)
attendance_split <- attendance_df %>% 
  initial_split(strata = playoffs)

nfl_train <- training(attendance_split)
nfl_test <- testing(attendance_split)
```


```{r}
# specifying a model

lm_spec <- linear_reg() %>% 
  set_engine("lm")

lm_spec
```

```{r}
# fitting a model
lm_fit <- lm_spec %>% 
  fit(weekly_attendance ~ ., data = nfl_train)

lm_fit %>% tidy() %>% arrange(-estimate)
```

```{r}
# specifying a random forest model
rf_spec <- rand_forest(mode = "regression") %>% 
  set_engine("ranger")

rf_spec
```

```{r}
# fitting a model
rf_fit <- rf_spec %>% 
  fit(weekly_attendance ~ ., data = nfl_train)

rf_fit
```

## Evaluate model

```{r}
results_train <- lm_fit %>% 
  predict(new_data = nfl_train) %>% 
  mutate(
    truth = nfl_train$weekly_attendance,
    model = 'lm'
  ) %>% 
  bind_rows(
    rf_fit %>% 
    predict(new_data = nfl_train) %>% 
    mutate(
      truth = nfl_train$weekly_attendance,
      model = 'rf'
    )
  )

results_test <- lm_fit %>% 
  predict(new_data = nfl_test) %>% 
  mutate(
    truth = nfl_test$weekly_attendance,
    model = 'lm'
  ) %>% 
  bind_rows(
    rf_fit %>% 
    predict(new_data = nfl_test) %>% 
    mutate(
      truth = nfl_test$weekly_attendance,
      model = 'rf'
    )
  )
```

```{r}
results_train %>% 
  group_by(model) %>% 
  yardstick::rmse(truth = truth, estimate = .pred)
```

```{r}
results_test %>% 
  group_by(model) %>% 
  yardstick::rmse(truth = truth, estimate = .pred)
```

```{r}
results_test %>% 
  mutate(train = "testing") %>% 
  bind_rows(results_train %>% 
  mutate(train = "training")) %>% 
  ggplot(aes(truth, .pred, color = model)) +
  geom_point(alpha = 0.5) +
  geom_abline(lty = 2, color = "gray80", size = 1.5) +
  facet_wrap(~train)
```

## Lets try again with resampling

```{r}
set.seed(1234)

nfl_folds <- vfold_cv(nfl_train, strata = playoffs)

nfl_folds
```

```{r}
rf_res <- fit_resamples(
  rf_spec,
  weekly_attendance ~ .,
  nfl_folds,
  control = control_resamples(save_pred = TRUE)
)

rf_res %>% 
  collect_metrics()
```


```{r}
rf_res %>%
  unnest(.predictions) %>%
  ggplot(aes(weekly_attendance, .pred, color = id)) +
  geom_abline(lty = 2, color = "gray80", size = 1.5) +
  geom_point(alpha = 0.5)
```

